server:
    port: 8999
spring:
    application:
        name: bi-portal-admin
    profiles:
        active: @environment@
mybatis-plus:
    type-aliases-package: com.yinlu.bi.portal.*.model
    mapper-locations: classpath:mapper/*.xml
    global-config:
        banner: false